apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30061
    protocol: TCP
  selector:
    app: nginx-v1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
  labels:
    version: v1
spec:
  replicas: 2
  selector:
    app: nginx-v1
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      volumes:
        - name: www
          nfs:
            server: example.com
            path: "/foo/bar/web1"
            readOnly: true
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: www
            mountPath: "/usr/share/nginx/html/"
