apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller-v2
  labels:
    version: v2
spec:
  replicas: 2
  selector:
    # this must match the label in the template below
    app: nginx-v2
  template:
    metadata:
      labels:
        app: nginx-v2
    spec:
      volumes:
        - name: www
          nfs:
            server: example.com
            # notice this path is different from the other RC
            path: "/foo/bar/web2"
            readOnly: true
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 8080
        volumeMounts:
          - name: www
            mountPath: "/usr/share/nginx/html/"
