apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
  labels:
    version: v1
spec:
  replicas: 2
  selector:
    #this must match the label in the template below
    app: nginx-v1
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      volumes:
        - name: www
          nfs:
            server: example.com
            # notice this path is different than the other RC
            path: "/foo/bar/web1"
            readOnly: true
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 8080
        volumeMounts:
          - name: www
            mountPath: "/usr/share/nginx/html/"
